# Generated by Django 6.0.4 on 2026-06-09 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='total_discount_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Descuento total otorgado en USD (precio de lista − precio de venta)', max_digits=12),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='discount_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Descuento aplicado a la línea (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='unit_list_price_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio de lista unitario en USD (antes de descuento)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_sale_price_usd',
            field=models.DecimalField(decimal_places=2, help_text='Precio unitario de venta en USD (neto, con descuento)', max_digits=10),
        ),
    ]
