# Generated by Django 6.0.4 on 2026-07-01 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_systemsettings_price_bands'),
        ('sales', '0002_sale_total_discount_usd_saleitem_discount_pct_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='control_number',
            field=models.CharField(blank=True, help_text='Número de control exigido por el SENIAT', max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='invoice_date',
            field=models.DateField(blank=True, help_text='Fecha de emisión de la factura fiscal', null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='invoice_file',
            field=models.FileField(blank=True, help_text='Archivo de la factura (PDF o imagen)', null=True, upload_to='facturas/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='sale',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Número de factura fiscal correlativo (SENIAT)', max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='iva_amount_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto de IVA en USD', max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='iva_rate',
            field=models.DecimalField(decimal_places=2, default=16.0, help_text='Porcentaje de IVA aplicado (por defecto 16%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_with_iva_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total a pagar en USD (base + IVA)', max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_with_iva_ves',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total a pagar en Bolívares (base + IVA)', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_sale_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base imponible de la venta en USD (sin IVA)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_sale_ves',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base imponible de la venta en Bolívares (sin IVA)', max_digits=18, null=True),
        ),
        migrations.CreateModel(
            name='DispatchOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='Número de orden de despacho correlativo (ej: OD-08052026-3)', max_length=40, unique=True)),
                ('status', models.CharField(choices=[('PEN', 'Pendiente'), ('PREP', 'En preparación'), ('DESP', 'Despachada'), ('ENT', 'Entregada'), ('ANU', 'Anulada')], default='PEN', max_length=4)),
                ('dispatch_date', models.DateField(blank=True, help_text='Fecha planificada/efectiva de despacho', null=True)),
                ('delivery_address', models.TextField(blank=True, help_text='Dirección de entrega')),
                ('carrier', models.CharField(blank=True, help_text='Transporte o responsable de la entrega', max_length=150)),
                ('received_by', models.CharField(blank=True, help_text='Persona que recibe la mercancía (recibí conforme)', max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario que generó la orden', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_orders', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(help_text='Venta a la que corresponde el despacho', on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_orders', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Orden de Despacho',
                'verbose_name_plural': 'Órdenes de Despacho',
                'db_table': 'dispatch_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Cantidad a despachar')),
                ('dispatch_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.dispatchorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_items', to='core.product')),
            ],
            options={
                'verbose_name': 'Línea de Orden de Despacho',
                'verbose_name_plural': 'Líneas de Orden de Despacho',
                'db_table': 'dispatch_order_items',
            },
        ),
        migrations.AddIndex(
            model_name='dispatchorder',
            index=models.Index(fields=['order_number'], name='dispatch_number_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchorder',
            index=models.Index(fields=['sale'], name='dispatch_sale_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchorder',
            index=models.Index(fields=['status'], name='dispatch_status_idx'),
        ),
    ]
