# Generated by Django 6.0.4 on 2026-07-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_backfill_sale_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='import_ref',
            field=models.CharField(blank=True, db_index=True, help_text='Referencia del presupuesto importado desde Excel (continuidad operativa); evita duplicados al reimportar', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='import_ref',
            field=models.CharField(blank=True, db_index=True, help_text='Referencia de la operación importada desde Excel (continuidad operativa); evita duplicados al reimportar', max_length=60, null=True),
        ),
    ]
