# Generated by Django 6.0.4 on 2026-07-23 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import F


def backfill_amount_paid(apps, schema_editor):
    """Marca las ventas ya "Completadas" como totalmente cobradas.

    El campo nace con default 0; para no dejar todo el histórico con saldo pendiente
    (que lo sacaría de "pagado" y confundiría la cobranza), las ventas COMP existentes
    se consideran cobradas por completo (abonado = total con IVA). Es **neutral para la
    analítica**: no cambia estados ni montos de ingreso/utilidad, solo la cobranza. No
    se crean filas de abono para el histórico (predata la funcionalidad)."""
    Sale = apps.get_model("sales", "Sale")
    Sale.objects.filter(status="COMP").update(amount_paid_usd=F("total_with_iva_usd"))


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_quote_import_ref_sale_import_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='amount_paid_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto abonado/cobrado en USD (suma de abonos). Saldo = total con IVA − abonado', max_digits=12),
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd', models.DecimalField(decimal_places=2, help_text='Monto del abono en USD', max_digits=12)),
                ('amount_ves', models.DecimalField(blank=True, decimal_places=2, help_text='Monto del abono en Bolívares (referencia a la tasa del día)', max_digits=18, null=True)),
                ('method', models.CharField(choices=[('EFE', 'Efectivo (Bs)'), ('DIV', 'Efectivo (divisas)'), ('PMO', 'Pago móvil'), ('TRA', 'Transferencia'), ('PDV', 'Punto de venta'), ('ZEL', 'Zelle'), ('OTR', 'Otro')], default='OTR', help_text='Medio de pago', max_length=3)),
                ('payment_date', models.DateField(help_text='Fecha del abono')),
                ('reference', models.CharField(blank=True, help_text='Referencia / nº de transacción', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, help_text='Usuario que registró el abono', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_payments', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(help_text='Venta a la que se aplica el abono', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Abono',
                'verbose_name_plural': 'Abonos',
                'db_table': 'sale_payments',
                'ordering': ['payment_date', 'id'],
                'indexes': [models.Index(fields=['sale'], name='sale_payments_sale_idx')],
            },
        ),
        migrations.RunPython(backfill_amount_paid, migrations.RunPython.noop),
    ]
