# Generated by Django 6.0.4 on 2026-07-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_sale_amount_paid_usd_salepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='delivery_cost_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cargo por despacho/flete en USD (se suma a la base imponible)', max_digits=12),
        ),
        migrations.AddField(
            model_name='quote',
            name='installation_cost_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cargo por instalación en USD (se suma a la base imponible)', max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='delivery_cost_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cargo por despacho/flete en USD (opcional; se suma a la base imponible)', max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='installation_cost_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cargo por instalación en USD (opcional; se suma a la base imponible)', max_digits=12),
        ),
    ]
