# Generated by Django 6.0.4 on 2026-07-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_quote_delivery_cost_usd_quote_installation_cost_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='eur_bcv_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Tasa Euro BCV vigente al emitir', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='eur_bcv_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Tasa Euro BCV al momento de la venta', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='bcv_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Tasa Dólar BCV vigente al emitir', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='parallel_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Tasa paralela vigente al emitir (referencial)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='bcv_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Tasa Dólar BCV al momento de la venta', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='parallel_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Tasa paralela al momento de la venta (referencial)', max_digits=12, null=True),
        ),
    ]
