# Generated by Django 6.0.4 on 2026-06-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_backfill_profile_personal_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('MANAGER', 'Gerente'), ('SELLER', 'Vendedor'), ('WAREHOUSE', 'Encargado de Inventario'), ('VIEWER', 'Consulta')], default='VIEWER', help_text='Rol de negocio que define los permisos del usuario', max_length=10),
        ),
    ]
