# Generated by Django 6.0.4 on 2026-06-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benchmarking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitormarketdata',
            name='source',
            field=models.CharField(choices=[('IG', 'Instagram'), ('FB', 'Facebook Marketplace'), ('WEB', 'Página Web Directa'), ('ML', 'Mercado Libre'), ('OTH', 'Otra Fuente')], default='WEB', max_length=3),
        ),
    ]
