# Generated by Django 6.0.4 on 2026-06-06 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benchmarking', '0002_alter_competitormarketdata_source'),
        ('core', '0002_alter_product_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitormarketdata',
            name='enriched_by',
            field=models.CharField(choices=[('DET', 'Determinista (reglas)'), ('LLM', 'Enriquecido por LLM')], default='DET', help_text='Procedencia del enriquecimiento de la fila (reglas vs. LLM)', max_length=3),
        ),
        migrations.AddField(
            model_name='competitormarketdata',
            name='exchange_rate_used',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Tasa Bs/USD aplicada para convertir (solo si el precio venía en VES)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='competitormarketdata',
            name='listing_key',
            field=models.CharField(blank=True, db_index=True, help_text='Clave estable del anuncio entre runs (fuente+url o fuente+competidor+producto)', max_length=64),
        ),
        migrations.AddField(
            model_name='competitormarketdata',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio convertido a USD al momento del scraping', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='competitormarketdata',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Producto propio equivalente (match automático; revisable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitor_observations', to='core.product'),
        ),
        migrations.AddField(
            model_name='competitormarketdata',
            name='product_match_score',
            field=models.FloatField(blank=True, help_text='Similitud [0–1] del match con el producto propio', null=True),
        ),
        migrations.AddField(
            model_name='competitormarketdata',
            name='rate_date',
            field=models.DateField(blank=True, help_text='Fecha de la ExchangeRate usada para la conversión', null=True),
        ),
        migrations.CreateModel(
            name='ScrapeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('IG', 'Instagram'), ('FB', 'Facebook Marketplace'), ('WEB', 'Página Web Directa'), ('ML', 'Mercado Libre'), ('OTH', 'Otra Fuente')], max_length=3)),
                ('query', models.JSONField(blank=True, default=list, help_text='URLs o términos de búsqueda del run')),
                ('params', models.JSONField(blank=True, default=dict, help_text='Parámetros del run (límite, competidor manual, etc.)')),
                ('apify_run_id', models.CharField(blank=True, max_length=100)),
                ('dataset_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('RUN', 'En ejecución'), ('OK', 'Completado'), ('ERR', 'Fallido')], default='RUN', max_length=3)),
                ('records_collected', models.IntegerField(default=0, help_text='Filas mapeadas desde el dataset')),
                ('records_saved', models.IntegerField(default=0, help_text='Filas que pasaron la validación y se guardaron')),
                ('records_discarded', models.IntegerField(default=0, help_text='Filas descartadas por la validación de calidad')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Run de Scraping',
                'verbose_name_plural': 'Runs de Scraping',
                'db_table': 'benchmarking_scrape_runs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['source', 'started_at'], name='scraperun_source_date_idx'), models.Index(fields=['dataset_id'], name='scraperun_dataset_idx')],
            },
        ),
        migrations.CreateModel(
            name='RejectedMarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('IG', 'Instagram'), ('FB', 'Facebook Marketplace'), ('WEB', 'Página Web Directa'), ('ML', 'Mercado Libre'), ('OTH', 'Otra Fuente')], max_length=3)),
                ('competitor_name', models.CharField(blank=True, max_length=150)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('rejection_reason', models.CharField(help_text='Motivo del descarte', max_length=255)),
                ('raw_metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scrape_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_records', to='benchmarking.scraperun')),
            ],
            options={
                'verbose_name': 'Dato de Mercado Descartado',
                'verbose_name_plural': 'Datos de Mercado Descartados',
                'db_table': 'benchmarking_rejected_market_data',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='competitormarketdata',
            name='scrape_run',
            field=models.ForeignKey(blank=True, help_text='Run de scraping que produjo esta fila (procedencia)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='benchmarking.scraperun'),
        ),
        migrations.AddIndex(
            model_name='competitormarketdata',
            index=models.Index(fields=['listing_key', 'scraped_at'], name='bmd_listing_date_idx'),
        ),
        migrations.AddIndex(
            model_name='competitormarketdata',
            index=models.Index(fields=['product', 'scraped_at'], name='bmd_product_date_idx'),
        ),
        migrations.AddIndex(
            model_name='rejectedmarketdata',
            index=models.Index(fields=['source', 'created_at'], name='rejected_source_date_idx'),
        ),
    ]
