# Generated by Django 6.0.4 on 2026-06-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benchmarking', '0003_competitormarketdata_enriched_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitormarketdata',
            name='posted_at',
            field=models.DateTimeField(blank=True, help_text='Fecha de publicación original del anuncio (solo Instagram); si está vacía se usa scraped_at', null=True),
        ),
    ]
