# Generated by Django 6.0.4 on 2026-06-20 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benchmarking', '0004_competitormarketdata_posted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitor',
            name='facebook',
        ),
    ]
