# Generated by Django 6.0.4 on 2026-06-06 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, choices=[('MESH', 'Malla Mesh'), ('BIPIEL', 'Bipiel'), ('FABRIC', 'Tela'), ('METAL', 'Metal'), ('WOOD', 'Madera/Melamina'), ('OTHER', 'Otro')], help_text='Material principal del producto', max_length=10, null=True),
        ),
    ]
