# Generated by Django 6.0.4 on 2026-06-13 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_basis', models.CharField(choices=[('PAR', 'Paralela'), ('BCV', 'BCV (oficial)'), ('AVG', 'Promedio BCV/Paralela')], default='PAR', help_text='Qué tasa usar para convertir USD→VES en ventas, presupuestos y reportes.', max_length=3)),
                ('rate_max_age_days', models.PositiveSmallIntegerField(default=2, help_text='Días de antigüedad a partir de los cuales la tasa se considera vencida (dispara alerta).')),
                ('exchange_rate_api_url', models.CharField(blank=True, default='https://pydolarve.org/api/v1/dollar', help_text='URL de la API pública para bajar la tasa (BCV + paralela).', max_length=300)),
                ('use_llm_enrichment', models.BooleanField(default=False, help_text='Activa el enriquecimiento de scrapers vía DeepSeek (requiere DEEPSEEK_API_KEY en el entorno).')),
                ('deepseek_model', models.CharField(blank=True, default='deepseek-chat', help_text='Modelo de DeepSeek a usar (p. ej. deepseek-chat).', max_length=100)),
                ('deepseek_base_url', models.CharField(blank=True, default='https://api.deepseek.com', help_text='Endpoint compatible con OpenAI para DeepSeek.', max_length=300)),
                ('enable_llm_report_narrative', models.BooleanField(default=True, help_text='Permite que el reporte ejecutivo PDF use prosa redactada por el LLM (si hay clave).')),
                ('use_vision_price_ocr', models.BooleanField(default=False, help_text='Activa el OCR de precios en imágenes de Instagram (EasyOCR; requiere el paquete instalado).')),
                ('ocr_languages', models.CharField(blank=True, default='es,en', help_text='Idiomas de EasyOCR, separados por comas (p. ej. es,en).', max_length=50)),
                ('ocr_use_gpu', models.BooleanField(default=False, help_text='Usar GPU para el OCR si hay CUDA disponible.')),
                ('ocr_max_images_per_post', models.PositiveSmallIntegerField(default=2, help_text='Cuántas imágenes leer por publicación.')),
                ('ocr_mag_ratio', models.DecimalField(decimal_places=2, default=2.0, help_text="Factor de ampliación de la imagen antes del OCR (ayuda a captar un '$' pequeño).", max_digits=4)),
                ('ocr_assume_usd_for_bare_number', models.BooleanField(default=False, help_text='Tratar un número sin símbolo de moneda como precio en USD (arriesgado; off por defecto).')),
                ('ocr_bare_number_max_usd', models.DecimalField(decimal_places=2, default=500.0, help_text="Tope de seguridad (USD) para un número 'desnudo' sin indicador de precio.", max_digits=8)),
                ('discard_instagram_without_price', models.BooleanField(default=False, help_text='Descartar posts de Instagram sin precio (por defecto se conservan: el precio rara vez está en el caption).')),
                ('scraper_default_limit', models.PositiveSmallIntegerField(default=50, help_text='Límite de resultados por defecto al lanzar un scraper.')),
                ('default_iva_pct', models.DecimalField(decimal_places=2, default=16.0, help_text='IVA por defecto (%) al crear un presupuesto.', max_digits=5)),
                ('default_quote_expiry_days', models.PositiveSmallIntegerField(default=15, help_text='Vigencia por defecto (días) de un presupuesto cuando no se indica fecha de vencimiento.')),
                ('company_name', models.CharField(blank=True, default='Inversiones Maescar, C.A.', help_text='Razón social, usada en el encabezado de presupuestos y reportes.', max_length=200)),
                ('company_rif', models.CharField(blank=True, help_text='RIF de la empresa.', max_length=30)),
                ('company_address', models.TextField(blank=True, help_text='Dirección fiscal.')),
                ('company_phone', models.CharField(blank=True, help_text='Teléfono de contacto.', max_length=50)),
                ('company_email', models.EmailField(blank=True, help_text='Correo de contacto.', max_length=254)),
                ('company_website', models.CharField(blank=True, help_text='Sitio web.', max_length=150)),
                ('company_logo_url', models.URLField(blank=True, help_text='URL del logo (PNG/JPG) para los documentos.', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuración del Sistema',
                'db_table': 'system_settings',
            },
        ),
    ]
