# Generated by Django 6.0.4 on 2026-06-20 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_systemsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='back_length_cm',
        ),
        migrations.RemoveField(
            model_name='product',
            name='back_width_cm',
        ),
        migrations.RemoveField(
            model_name='product',
            name='desk_height_cm',
        ),
        migrations.RemoveField(
            model_name='product',
            name='desk_length_cm',
        ),
        migrations.RemoveField(
            model_name='product',
            name='desk_width_cm',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='max_height_cm',
        ),
        migrations.RemoveField(
            model_name='product',
            name='min_height_cm',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seat_length_cm',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seat_width_cm',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='phone',
        ),
    ]
