# Generated by Django 6.0.4 on 2026-06-20 15:09

import apps.core.price_band_defaults
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='price_bands',
            field=models.JSONField(blank=True, default=apps.core.price_band_defaults.default_price_bands, help_text='Rangos de precio plausibles (USD) por categoría para la validación de datos scrapeados. Estructura: {categories: {<cat>: {min, max}}, default: {min, max}}.'),
        ),
    ]
