# Generated by Django 6.0.4 on 2026-07-04 01:46

from django.db import migrations, models


def seed_average_cost(apps, schema_editor):
    """Inicializa el costo promedio ponderado de los productos existentes.

    Al introducir el costeo por promedio ponderado móvil, cada producto arranca su
    promedio en su precio de compra actual (`purchase_price_usd`). Así el CMV de las
    ventas nuevas es idéntico al anterior hasta que una entrada real mueva el promedio,
    y la historia/métricas de ML no cambian.
    """
    Product = apps.get_model("core", "Product")
    Product.objects.filter(average_cost_usd__isnull=True).exclude(
        purchase_price_usd__isnull=True
    ).update(average_cost_usd=models.F("purchase_price_usd"))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_systemsettings_price_bands'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_cost_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo promedio ponderado móvil en USD (base del CMV; lo recalcula el inventario en cada entrada)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de compra actual en USD (referencia / última compra)', max_digits=10, null=True),
        ),
        migrations.RunPython(seed_average_cost, migrations.RunPython.noop),
    ]
