# Generated by Django 6.0.4 on 2026-07-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_seed_company_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='training_cutoff_date',
            field=models.DateField(blank=True, help_text='Fecha de corte del entrenamiento: los datos POSTERIORES a esta fecha se excluyen de las series con las que se entrenan los modelos, y el pronóstico arranca justo después del corte. Útil cuando se cargaron datos de prueba recientes que no deben contaminar los modelos. Vacío = usar todo el historial.', null=True),
        ),
    ]
