# Generated by Django 6.0.4 on 2026-07-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_systemsettings_training_cutoff_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='eur_bcv_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Tasa Euro BCV oficial (Bs por 1 EUR) — operativa', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='bcv_rate',
            field=models.DecimalField(decimal_places=4, help_text='Tasa Dólar BCV oficial (Bs por 1 USD) — operativa', max_digits=12),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='parallel_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Tasa paralela referencial (Bs por 1 USD) — solo análisis, no se factura con ella', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='rate_basis',
            field=models.CharField(choices=[('BCV', 'Dólar BCV (oficial)'), ('EUR', 'Euro BCV (oficial)'), ('PAR', 'Paralelo (referencial)'), ('AVG', 'Promedio Dólar BCV/Paralelo')], default='BCV', help_text='Qué tasa usar para convertir USD→VES en ventas, presupuestos y reportes. Lo normal es una de las oficiales (Dólar BCV o Euro BCV).', max_length=3),
        ),
    ]
