# Generated by Django 6.0.4 on 2026-07-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rate_basis_to_bcv'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpricehistory',
            name='eur_bcv_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Tasa Euro BCV en el momento del cambio', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='productpricehistory',
            name='bcv_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Tasa Dólar BCV en el momento del cambio', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='productpricehistory',
            name='parallel_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Tasa paralela en el momento del cambio (referencial)', max_digits=12, null=True),
        ),
    ]
