# Generated by Django 6.0.4 on 2026-07-29 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_productpricehistory_eur_bcv_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='rates_ignore_training_cutoff',
            field=models.BooleanField(default=False, help_text='Exceptúa a los pronósticos de TASA DE CAMBIO de la fecha de corte: se entrenan siempre con las tasas más recientes. Se usa cuando el corte existe por datos de prueba de ventas, pero las tasas cargadas sí son reales. No afecta a los demás modelos.'),
        ),
    ]
