# Generated by Django 6.0.4 on 2026-07-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_systemsettings_rates_ignore_training_cutoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='go_live_date',
            field=models.DateField(blank=True, help_text='Fecha de puesta en marcha del sistema. Lo registrado ANTES de esta fecha se considera carga histórica inicial y no genera tareas pendientes (p. ej. las entradas de inventario anteriores no se piden costear, porque nunca tuvieron factura asociada). Vacío = tratar todo el historial como operación real.', null=True),
        ),
    ]
