# Generated by Django 6.0.4 on 2026-04-28 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorMarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor_name', models.CharField(blank=True, help_text='Nombre de la empresa competidora (ej. OficinaTotal)', max_length=150, null=True)),
                ('source', models.CharField(choices=[('IG', 'Instagram'), ('FB', 'Facebook Marketplace'), ('WEB', 'Página Web Directa'), ('OTH', 'Otra Fuente')], default='WEB', max_length=3)),
                ('url', models.URLField(blank=True, help_text='Enlace directo al recurso de donde se obtuvo la información', max_length=500, null=True)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, help_text='Categoría normalizada (ej. Sillería, Escritorios)', max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio detectado', max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, default='USD', help_text='Moneda (USD o VES)', max_length=3, null=True)),
                ('lead_time_days', models.IntegerField(blank=True, help_text='Tiempo de entrega estimado en días (si aplica)', null=True)),
                ('is_in_stock', models.BooleanField(blank=True, default=True, help_text='¿El producto marca disponibilidad?', null=True)),
                ('promotions', models.CharField(blank=True, help_text="Etiquetas de oferta, ej: 'Envío Gratis', '15% OFF'", max_length=255, null=True)),
                ('raw_metadata', models.JSONField(blank=True, help_text='Guarda aquí datos extra: likes de IG, rating de vendedor en FB, etc.', null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora exacta de la extracción')),
            ],
            options={
                'verbose_name': 'Dato de Mercado Competitivo',
                'verbose_name_plural': 'Datos de Mercado Competitivo',
                'db_table': 'competitor_market_data',
                'ordering': ['-scraped_at'],
                'indexes': [models.Index(fields=['competitor_name', 'scraped_at'], name='competitor__competi_dcf143_idx'), models.Index(fields=['category', 'scraped_at'], name='competitor__categor_6985be_idx')],
            },
        ),
    ]
