# Generated by Django 6.0.4 on 2026-07-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitor_market_data', '0002_delete_competitormarketdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Nombre descriptivo de la programación', max_length=150)),
                ('source', models.CharField(choices=[('instagram', 'Instagram'), ('website', 'Sitios Web'), ('mercadolibre', 'Mercado Libre')], max_length=20)),
                ('urls', models.JSONField(default=list, help_text='URLs (o términos de búsqueda para Mercado Libre) a scrapear')),
                ('competitor_name', models.CharField(blank=True, help_text='Nombre del competidor (solo Sitios Web, opcional)', max_length=150)),
                ('limit', models.PositiveIntegerField(default=50, help_text='Límite de resultados por corrida')),
                ('frequency', models.CharField(choices=[('DAILY', 'Diaria'), ('WEEKLY', 'Semanal'), ('BIWEEKLY', 'Quincenal'), ('MONTHLY', 'Mensual')], default='MONTHLY', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, help_text='Última vez que se ejecutó automáticamente', null=True)),
                ('next_run_at', models.DateTimeField(help_text='Próxima ejecución programada (se dispara al iniciar sesión el admin si ya venció)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Programación de Scraping',
                'verbose_name_plural': 'Programaciones de Scraping',
                'db_table': 'scraper_schedules',
                'ordering': ['source', 'name', 'id'],
            },
        ),
    ]
