# Generated by Django 6.0.4 on 2026-07-04 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='unit_cost_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo unitario en USD del movimiento: precio de compra en las entradas (insumo del costo promedio ponderado) y costo promedio aplicado en las salidas por venta (trazabilidad del CMV).', max_digits=10, null=True),
        ),
    ]
