# Generated by Django 6.0.4 on 2026-07-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorymovement_unit_cost_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='import_ref',
            field=models.CharField(blank=True, db_index=True, help_text='Referencia del movimiento importado desde Excel (continuidad operativa); evita duplicados al reimportar', max_length=60, null=True),
        ),
    ]
