# Generated by Django 6.0.4 on 2026-07-24 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventorymovement_import_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='verified',
            field=models.BooleanField(default=False, help_text='¿Almacén verificó que este movimiento ocurrió físicamente?'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de la verificación', null=True),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Usuario (almacén/admin) que verificó el movimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_movements', to=settings.AUTH_USER_MODEL),
        ),
    ]
