# Generated by Django 6.0.4 on 2026-07-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventorymovement_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='cost_invoice_file',
            field=models.FileField(blank=True, help_text='Archivo de la factura de compra del proveedor (PDF o imagen) que respalda el costo unitario de la entrada. El nº de factura va en `reference`.', null=True, upload_to='facturas_compra/%Y/%m/'),
        ),
    ]
