# Generated by Django 6.0.4 on 2026-06-13 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_username', models.CharField(blank=True, help_text='Nombre de usuario al momento del hecho (foto)', max_length=150)),
                ('actor_role', models.CharField(blank=True, help_text='Rol del usuario al momento del hecho (foto)', max_length=10)),
                ('action', models.CharField(choices=[('SALE_CREATE', 'Venta registrada'), ('SALE_VOID', 'Venta anulada'), ('QUOTE_CREATE', 'Presupuesto creado'), ('INVENTORY_MOVEMENT', 'Movimiento de inventario'), ('SCRAPE_START', 'Scraping iniciado'), ('REPORT_GENERATE', 'Reporte ejecutivo generado'), ('USER_CREATE', 'Usuario creado'), ('SETTINGS_UPDATE', 'Configuración actualizada'), ('RATE_UPDATE', 'Tasa de cambio cargada'), ('PRODUCT_CREATE', 'Producto creado'), ('PRODUCT_UPDATE', 'Producto actualizado'), ('CUSTOMER_CREATE', 'Cliente creado'), ('CUSTOMER_UPDATE', 'Cliente actualizado'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('LOG_PURGE', 'Registros de auditoría purgados')], help_text='Acción auditada', max_length=32)),
                ('category', models.CharField(choices=[('VENTAS', 'Ventas'), ('INVENTARIO', 'Inventario'), ('SCRAPERS', 'Datos externos'), ('REPORTES', 'Reportes'), ('USUARIOS', 'Usuarios'), ('CATALOGO', 'Catálogo'), ('CLIENTES', 'Clientes'), ('CONFIG', 'Configuración'), ('AUTH', 'Autenticación')], help_text='Área a la que pertenece la acción', max_length=12)),
                ('description', models.CharField(help_text='Resumen legible de lo ocurrido, en español', max_length=500)),
                ('target_model', models.CharField(blank=True, help_text='Modelo del objeto afectado', max_length=50)),
                ('target_id', models.CharField(blank=True, help_text='Identificador del objeto afectado', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Detalles estructurados adicionales (montos, conteos, etc.)')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Dirección IP desde la que se ejecutó la acción', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Usuario que ejecutó la acción (nulo si la realizó el sistema)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'created_at'], name='audit_cat_date_idx'), models.Index(fields=['action'], name='audit_action_idx'), models.Index(fields=['actor'], name='audit_actor_idx')],
            },
        ),
    ]
