# Generated by Django 6.0.4 on 2026-06-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('SALE_CREATE', 'Venta registrada'), ('SALE_VOID', 'Venta anulada'), ('QUOTE_CREATE', 'Presupuesto creado'), ('INVENTORY_MOVEMENT', 'Movimiento de inventario'), ('SCRAPE_START', 'Scraping iniciado'), ('REPORT_GENERATE', 'Reporte ejecutivo generado'), ('USER_CREATE', 'Usuario creado'), ('SETTINGS_UPDATE', 'Configuración actualizada'), ('RATE_UPDATE', 'Tasa de cambio cargada'), ('PRODUCT_CREATE', 'Producto creado'), ('PRODUCT_UPDATE', 'Producto actualizado'), ('CUSTOMER_CREATE', 'Cliente creado'), ('CUSTOMER_UPDATE', 'Cliente actualizado'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('PASSWORD_RESET_REQUEST', 'Solicitud de recuperación de contraseña'), ('PASSWORD_RESET', 'Contraseña restablecida'), ('LOG_PURGE', 'Registros de auditoría purgados')], help_text='Acción auditada', max_length=32),
        ),
    ]
