# Generated by Django 6.0.4 on 2026-06-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('SALE_CREATE', 'Venta registrada'), ('SALE_VOID', 'Venta anulada'), ('QUOTE_CREATE', 'Presupuesto creado'), ('INVENTORY_MOVEMENT', 'Movimiento de inventario'), ('SCRAPE_START', 'Scraping iniciado'), ('REPORT_GENERATE', 'Reporte ejecutivo generado'), ('MODELS_RETRAIN', 'Modelos predictivos reentrenados'), ('USER_CREATE', 'Usuario creado'), ('SETTINGS_UPDATE', 'Configuración actualizada'), ('RATE_UPDATE', 'Tasa de cambio cargada'), ('PRODUCT_CREATE', 'Producto creado'), ('PRODUCT_UPDATE', 'Producto actualizado'), ('CUSTOMER_CREATE', 'Cliente creado'), ('CUSTOMER_UPDATE', 'Cliente actualizado'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('PASSWORD_RESET_REQUEST', 'Solicitud de recuperación de contraseña'), ('PASSWORD_RESET', 'Contraseña restablecida'), ('LOG_PURGE', 'Registros de auditoría purgados')], help_text='Acción auditada', max_length=32),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='category',
            field=models.CharField(choices=[('VENTAS', 'Ventas'), ('INVENTARIO', 'Inventario'), ('SCRAPERS', 'Datos externos'), ('REPORTES', 'Reportes'), ('USUARIOS', 'Usuarios'), ('CATALOGO', 'Catálogo'), ('CLIENTES', 'Clientes'), ('CONFIG', 'Configuración'), ('AUTH', 'Autenticación'), ('ANALITICA', 'Analítica')], help_text='Área a la que pertenece la acción', max_length=12),
        ),
    ]
