# Generated by Django 6.0.4 on 2026-07-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('SALE_CREATE', 'Venta registrada'), ('SALE_VOID', 'Venta anulada'), ('SALE_INVOICE', 'Venta facturada'), ('QUOTE_CREATE', 'Presupuesto creado'), ('QUOTE_CONVERT', 'Presupuesto convertido a venta'), ('DISPATCH_CREATE', 'Orden de despacho generada'), ('DISPATCH_UPDATE', 'Orden de despacho actualizada'), ('INVENTORY_MOVEMENT', 'Movimiento de inventario'), ('SCRAPE_START', 'Scraping iniciado'), ('SCRAPE_STOP', 'Scraping detenido'), ('REPORT_GENERATE', 'Reporte ejecutivo generado'), ('MODELS_RETRAIN', 'Modelos predictivos reentrenados'), ('USER_CREATE', 'Usuario creado'), ('SETTINGS_UPDATE', 'Configuración actualizada'), ('RATE_UPDATE', 'Tasa de cambio cargada'), ('PRODUCT_CREATE', 'Producto creado'), ('PRODUCT_UPDATE', 'Producto actualizado'), ('CUSTOMER_CREATE', 'Cliente creado'), ('CUSTOMER_UPDATE', 'Cliente actualizado'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('PASSWORD_RESET_REQUEST', 'Solicitud de recuperación de contraseña'), ('PASSWORD_RESET', 'Contraseña restablecida'), ('DB_BACKUP', 'Respaldo de base de datos generado'), ('LOG_PURGE', 'Registros de auditoría purgados'), ('DATA_IMPORT', 'Datos importados desde Excel'), ('DATA_EXPORT', 'Datos exportados a Excel')], help_text='Acción auditada', max_length=32),
        ),
    ]
