# Generated by Django 6.0.4 on 2026-06-06 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('STOCK_B', 'Quiebre de Stock'), ('STOCK_O', 'Sobrestock'), ('PRICE', 'Cambio de Precio Competidor'), ('DEMAND', 'Caída de Demanda'), ('GOAL', 'Meta Cumplida'), ('RATE', 'Tasa de Cambio Desactualizada')], max_length=7),
        ),
    ]
