# Generated by Django 6.0.4 on 2026-06-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_alert_alert_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionlog',
            name='model_type',
            field=models.CharField(choices=[('DEMAND', 'Pronóstico de Demanda'), ('PRICE', 'Tendencia de Precios'), ('SEASON', 'Patrón Estacional'), ('BENCH', 'Benchmarking de Competidores'), ('SALES', 'Pronóstico de Ventas e Ingresos'), ('RATE', 'Pronóstico de Tasa de Cambio'), ('PROFIT', 'Pronóstico de Utilidad y Margen'), ('INVENT', 'Reabastecimiento de Inventario'), ('QUOTE', 'Conversión de Presupuestos')], max_length=6),
        ),
    ]
