# Generated by Django 6.0.4 on 2026-06-20 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_predictionlog_model_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='competitor',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='product',
        ),
        migrations.RemoveField(
            model_name='predictionlog',
            name='model_file_path',
        ),
    ]
