# Generated by Django 6.0.4 on 2026-07-04 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_remove_alert_competitor_remove_alert_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='audience',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='alert',
            name='dedupe_key',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='alert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('STOCK_B', 'Quiebre de Stock'), ('STOCK_P', 'Quiebre de Stock Previsto'), ('STOCK_O', 'Sobrestock'), ('PRICE', 'Cambio de Precio Competidor'), ('DEMAND', 'Caída de Demanda'), ('GOAL', 'Meta Cumplida'), ('RATE', 'Tasa de Cambio Desactualizada')], max_length=7),
        ),
        migrations.CreateModel(
            name='AlertRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='analytics.alert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lectura de Alerta',
                'verbose_name_plural': 'Lecturas de Alertas',
                'db_table': 'alert_reads',
                'indexes': [models.Index(fields=['user', 'alert'], name='alertread_user_alert_idx')],
                'unique_together': {('alert', 'user')},
            },
        ),
    ]
