# Generated by Django 6.0.4 on 2026-07-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_trainingrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('STOCK_B', 'Quiebre de Stock'), ('STOCK_P', 'Quiebre de Stock Previsto'), ('STOCK_O', 'Sobrestock'), ('PRICE', 'Cambio de Precio Competidor'), ('DEMAND', 'Caída de Demanda'), ('GOAL', 'Meta Cumplida'), ('RATE', 'Tasa de Cambio Desactualizada'), ('DISP', 'Despacho Pendiente')], max_length=7),
        ),
    ]
