# Generated by Django 6.0.4 on 2026-07-25 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_alter_alert_alert_type'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='kpi',
            name='kpis_name_period_idx',
        ),
        migrations.RemoveIndex(
            model_name='kpi',
            name='kpis_category_idx',
        ),
        migrations.DeleteModel(
            name='KPI',
        ),
    ]
